[package]
name = "tailr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
regex = "1.11.1"
num = "0.4.3"
once_cell = "1.20.2"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
rand = "0.8.5"
anyhow = "1.0.95"
pretty_assertions = "1.4.1"